---
title: "Analyze data"
output:
  pdf_document: default
  html_notebook: default
---

```{r message=FALSE, warning=FALSE}
library(dplyr)
library(tidygraph)
library(rtweet)
library(ggraph)
library(stringr)
library(grid)
library(gridExtra)
```

# Full Graph

```{r read the graph}
graph <- readRDS("retweet_graph.rds")
```

## A cell to remove the weighting by number of retweets the results stay robust!

```{r remove weights}
graph %>% 
  activate(edges) %>% 
  mutate(weight = 1) -> graph
```

```{r plot the graph}
graph %>% 
  ggraph("fr") +
    geom_edge_link() + 
    geom_node_point(aes(color=gruppo), size=3) +
    scale_colour_discrete(name="Party",
                          breaks=c("ITALIA VIVA",
                                   "PARTITO DEMOCRATICO",
                                   "FORZA ITALIA - BERLUSCONI PRESIDENTE",
                                   "LEGA - SALVINI PREMIER",
                                   "LIBERI E UGUALI",
                                   "MISTO",
                                   "MOVIMENTO 5 STELLE"),
                          labels=c("Italia Viva",
                                   "Partito Democratico",
                                   "Forza Italia",
                                   "Lega",
                                   "liberi e Uguali",
                                   "Misto",
                                   "Movimento 5 Stelle"))
```

```{r plot the graph without unconnected graphs}
graph %>% 
  activate(nodes) %>% 
  mutate(kcore=node_coreness()) %>% 
  filter(kcore > 0) %>% 
  ggraph("fr") +
    geom_edge_link() + 
    geom_node_point(aes(color=gruppo), size=3) +
    scale_colour_discrete(name="Party",
                          breaks=c("ITALIA VIVA",
                                   "PARTITO DEMOCRATICO",
                                   "FORZA ITALIA - BERLUSCONI PRESIDENTE",
                                   "LEGA - SALVINI PREMIER",
                                   "LIBERI E UGUALI",
                                   "MISTO",
                                   "MOVIMENTO 5 STELLE",
                                   "FRATELLI D'ITALIA"),
                          labels=c("Italia Viva",
                                   "Partito Democratico",
                                   "Forza Italia",
                                   "Lega",
                                   "Liberi e Uguali",
                                   "Misto",
                                   "Movimento 5 Stelle",
                                   "Fratelli d'Italia"))
ggsave("italian_chamber.png")
```

```{r compute assortativity}
graph %>% 
  activate(nodes) %>% 
  mutate(ass = graph_assortativity(attr = gruppo)) %>%
  pull(ass) %>% 
  head(1) -> assort
assort
```

```{r bootstrap the assortativity}
permassort <- NULL
for (i in 1:1000){
  graph %>% 
  activate(nodes) %>% 
  mutate(ass = graph_assortativity(attr = sample(gruppo))) %>%
  pull(ass) %>% 
  head(1) -> res
  permassort <- c(permassort, res)
}

permassort = data.frame(permassort)

ggplot(permassort, aes(x=permassort)) +
  geom_histogram(binwidth = 0.005) +
  geom_vline(xintercept = assort, colour = "red") +
  annotate("text", x=assort, y = 200, 
           label = as.character(round(assort, digits = 3)),
           size=3, angle=90, vjust=-0.4, hjust=0, colour = "red") +
  coord_cartesian(xlim = c(-1,1)) + 
  labs(x = "", y = "Count", title = "Assortativity Score") +
  scale_fill_viridis_d()
ggsave("chamber_assort_bootstrap.png")
```

# Party-Split Graph

```{r load graph}
graph_split <- readRDS("retweet_graph_split.rds")
```

## A cell to remove the weighting by number of retweets the results stay robust!

```{r remove weights split}
graph_split %>% 
  activate(edges) %>% 
  mutate(weight = 1) -> graph_split
```

```{r plot graph}
graph_split %>% 
  ggraph("fr") + 
  geom_edge_link() + 
  geom_node_point(aes(color=gruppo), size=3) + 
  scale_colour_manual(name="Party",
                      breaks=c("ITALIA VIVA", "PARTITO DEMOCRATICO"),
                      labels=c("Italia Viva", "Partito Democratico"),
                      values=c("#ffcf20ff", "#541352ff"))
ggsave("split_graph.png")
```

```{r compute assortativity split}
graph_split %>% 
  activate(nodes) %>% 
  mutate(ass = graph_assortativity(attr = gruppo)) %>%
  pull(ass) %>% 
  head(1) -> assort_split
assort_split
```

```{r bootstrap assortativity}
permassort_split <- NULL
for (i in 1:10000){
  graph_split %>% 
  activate(nodes) %>% 
  mutate(ass = graph_assortativity(attr = sample(gruppo))) %>%
  pull(ass) %>% 
  head(1) -> res
  permassort_split <- c(permassort_split, res)
}
permassort_split = data.frame(permassort_split)

ggplot(permassort_split, aes(x=permassort_split)) +
  geom_histogram(binwidth = 0.005) +
  geom_vline(xintercept = assort_split, colour =  "red") +
  annotate("text", x=assort_split, y = 500, 
           label = as.character(round(assort_split, digits = 3)),
           size=3, angle=90, vjust=-0.4, hjust=0, colour = "red") +
  coord_cartesian(xlim = c(-1,1)) + 
  labs(x = "", y = "Count", title = "Assortativity Score") +
  scale_fill_viridis_d()
ggsave("assort_split_bootstrap.png")
```

# Analyzing the split

```{r predict the split}
graph_split %>% 
  activate(nodes) %>% 
  mutate(predicted=as.character(group_spinglass(spins=2)), party=gruppo) -> split
```

```{r compute assortativity predict}
split %>% 
  activate(nodes) %>% 
  mutate(ass = graph_assortativity(attr = predicted)) %>%
  pull(ass) %>% 
  head(1) -> assort_predict
assort_predict
```

```{r bootstrap assortativity with predicted}
ggplot(permassort_split, aes(x=permassort_split)) +
  geom_histogram(binwidth = 0.005) +
  geom_vline(xintercept = assort_split, colour =  "red") +
  annotate("text", x=assort_split, y = 500, 
           label = as.character(round(assort_split, digits = 3)),
           size=3, angle=90, vjust=-0.4, hjust=0, colour = "red") +
  geom_vline(xintercept = assort_predict, colour =  "#ffcf20ff") +
  annotate("text", x=assort_predict, y = 700, 
           label = as.character(round(assort_predict, digits = 3)),
           size=3, angle=90, vjust=-0.4, hjust=0, colour = "#ffcf20ff")+
  coord_cartesian(xlim = c(-1,1)) + 
  labs(x = "", y = "Count", title = "Assortativity Score") +
  scale_fill_viridis_d()
ggsave("assort_split_bootstrap_predict.png")
```


```{r compute counts}
as_tibble(split) %>% 
  count(predicted)

as_tibble(split) %>% 
  count(party)
```

```{r compute confusion matrix}
as_tibble(split) %>% 
  group_by(party) %>% 
  count(predicted) -> confusion
confusion
```

```{r plot label assignments}
as_tibble(split) %>% 
  mutate(party = case_when(party == "PARTITO DEMOCRATICO" ~"Partito Democartico (PD)",
                           party == "ITALIA VIVA" ~ "Italia Viva (IV)")) %>% 
  ggplot(aes(x=party, fill=predicted)) +
    geom_bar(position = 'dodge') +
    labs(x = "Party", y = "Count", title = "Prediction per Party") +
    scale_fill_viridis_d(name  ="Predicted Party",
                         breaks=c("1", "2"),
                         labels=c("IV", "PD")) ->
    plot_party_predicted

as_tibble(split) %>% 
  mutate(predicted = case_when(predicted == "2" ~"Partito Democartico (PD)",
                               predicted == "1" ~ "Italia Viva (IV)")) %>% 
  ggplot(aes(x=predicted, fill=party)) +
    geom_bar(position = 'dodge') +
    labs(x = "Prediction", y = "Count", title = "Party per Prediction") +
    scale_fill_viridis_d(name  ="Actual Party    ",
                        breaks=c("ITALIA VIVA", "PARTITO DEMOCRATICO"),
                        labels=c("IV", "PD")) ->
    plot_predicted_party

grid.arrange(plot_predicted_party, plot_party_predicted, nrow = 2, 
             top=textGrob("Predicted Party Split", 
                          gp = gpar(fontsize = 13, fontface = 'bold'))
             ) -> split_distribution
ggsave(plot = split_distribution, "split_distribution.png")
```

## Beware that the layout of the graph is random

### Different graphs cannot be compared directly

```{r plot predicted graph}
split %>% 
  ggraph("fr")  + 
    geom_edge_link(edge_alpha = 0.5) + 
    geom_node_point(aes(color=predicted),size=3) + 
    labs(title = "Predicted Split") +
    scale_colour_manual(name  ="Predicted Party",
                        breaks=c("1", "2"),
                        labels=c("Italia Viva", "Partito Democratico"),
                        values=c("#ffcf20ff", "#541352ff")) -> 
    plot_predicted
plot_predicted
```

```{r plot actual graph}
split %>% 
  ggraph(layout = "fr")  + 
    geom_edge_link(edge_alpha = 0.5) + 
    geom_node_point(aes(color=party),size=3) + 
    labs(title = "Actual Split") +
    scale_colour_manual(name  ="Party",
                          breaks=c("ITALIA VIVA", "PARTITO DEMOCRATICO"),
                          labels=c("Italia Viva", "Partito Democratico"),
                          values=c("#ffcf20ff", "#541352ff")) -> 
    plot_party
plot_party
```

```{r plot interssect graph}
split %>% 
  ggraph("fr")  + 
    geom_edge_link(edge_alpha = 0.5) + 
    geom_node_point(aes(color=party, shape = predicted),size=3) + 
    labs(title = "Predicted and Actual Split") +
    scale_colour_manual(name="Party",
                          breaks=c("ITALIA VIVA", "PARTITO DEMOCRATICO"),
                          labels=c("Italia Viva", "Partito Democratico"),
                          values=c("#ffcf20ff", "#541352ff")) +
    scale_shape_discrete(name="Predicted Party",
                         breaks=c("1", "2"),
                         labels=c("Italia Viva", "Partito Democratico")) -> 
    plot_intersect
plot_intersect
ggsave("split_graph.png")
```

```{r compute metrics of IV classificatoin}
TP <- as.numeric(confusion[1,3])
TN <- as.numeric(confusion[4,3])
FP <- as.numeric(confusion[3,3])
FN <- as.numeric(confusion[2,3])

accuracy <- (TP+TN)/(TP+TN+FN+FP)
precision <- (TP)/(TP+FP)
recall <- (TP)/(TP+FN)
f1 <- 2*(recall*precision)/(precision+recall)
```

```{r print metrics}
print("--- Accuracy ---")
print(accuracy)
print("--- Precision ---")
print(precision)
print("--- Recall ---")
print(recall)
print("--- F1 Score ---")
print(f1)
```

```{r bootsrap metrics}
permassort <- NULL
perm_acc <- NULL
perm_prec <- NULL
perm_rec <- NULL
perm_f1 <- NULL
nrows <- nrow(as_tibble(split))

for (i in 1:10000){
  as_tibble(split) %>% 
    mutate(predicted = sample(c(1,2), nrows, replace=T)) %>% 
    group_by(party) %>% 
    count(sample(predicted)) -> confusion

  IV1 <- as.numeric(confusion[1,3])
  IV2 <- as.numeric(confusion[2,3])
  PD1 <- as.numeric(confusion[3,3])
  PD2 <- as.numeric(confusion[4,3])
  
  if ( IV1/(IV1+IV2) >= PD1/(PD1+PD2) ){
    TP <- IV1
    TN <- IV2
    FP <- PD1
    TN <- PD2
  }
  else {
    TP <- IV2
    TN <- IV1
    FP <- PD2
    TN <- PD1
  }
  
  perm_acc <- c(perm_acc, (TP+TN)/(TP+TN+FN+FP))
  perm_prec <- c(perm_prec, (TP)/(TP+FP))
  perm_rec <- c(perm_rec, (TP)/(TP+FN))
  perm_f1 <- c(perm_f1, 2*((TP)/(TP+FN)*(TP)/(TP+FP))/((TP)/(TP+FP)+(TP)/(TP+FN)))
}
```

```{r plot histograms of bootstrap metrics}
perm_acc = data.frame(perm_acc)

ggplot(perm_acc, aes(x=perm_acc)) +
  geom_histogram(binwidth = 0.02) +
  geom_vline(xintercept = accuracy, colour = "red") +
  annotate("text", x=accuracy, y = 1000, label = as.character(round(accuracy, digits = 3)),
           size=3, angle=90, vjust=-0.4, hjust=0, colour = "red") +
  coord_cartesian(xlim = c(0,1)) + 
  labs(x = "", y = "Count", title = "Accuracy") +
  scale_fill_viridis_d() ->
  plot_acc

perm_prec = data.frame(perm_prec)

ggplot(perm_prec, aes(x=perm_prec)) +
  geom_histogram(binwidth = 0.02) +
  geom_vline(xintercept = precision, colour = "red") +
  annotate("text", x=precision, y = 1000, label = as.character(round(precision, digits = 3)),
           size=3, angle=90, vjust=-0.4, hjust=0, colour = "red") +
  coord_cartesian(xlim = c(0,1)) +
  labs(x = "", y = "Count", title = "Precision") +
  scale_fill_viridis_d() ->
  plot_prec


perm_rec = data.frame(perm_rec)

ggplot(perm_rec, aes(x=perm_rec)) +
  geom_histogram(binwidth = 0.02) +
  geom_vline(xintercept = recall, colour = "red") +
  annotate("text", x=recall, y = 1000, label = as.character(round(recall, digits = 3)),
           size=3, angle=90, vjust=-0.4, hjust=0, colour = "red") +
  coord_cartesian(xlim = c(0,1)) +
  labs(x = "", y = "Count", title = "Recall") +
  scale_fill_viridis_d() ->
  plot_rec

perm_f1 = data.frame(perm_f1)

ggplot(perm_f1, aes(x=perm_f1)) +
  geom_histogram(binwidth = 0.02) +
  geom_vline(xintercept = f1, colour = "red") +
  annotate("text", x=f1, y = 1000, label = as.character(round(f1, digits = 3)),
           size=3, angle=90, vjust=-0.4, hjust=0, colour = "red") +
  coord_cartesian(xlim = c(0,1)) +
  labs(x = "", y = "Count", title = "F1-Score") +
  scale_fill_viridis_d() ->
  plot_f1

grid.arrange(plot_acc, plot_prec, plot_rec, plot_f1, nrow = 2, ncol = 2, 
             top=textGrob("Random Clustering vs. Spinglass \n N = 10000 ", 
                          gp = gpar(fontsize = 13, fontface = 'bold'))
             ) -> split_metrics
ggsave(plot = split_metrics, "split_metrics.png")
```
